export const india = {
  name: "India",
  isoCode: "IN",
};

export const states = [
  { name: "Andhra Pradesh", isoCode: "AP" },
  { name: "Arunachal Pradesh", isoCode: "AR" },
  { name: "Assam", isoCode: "AS" },
  { name: "Bihar", isoCode: "BR" },
  { name: "Chhattisgarh", isoCode: "CT" },
  { name: "Goa", isoCode: "GA" },
  { name: "Gujarat", isoCode: "GJ" },
  { name: "Haryana", isoCode: "HR" },
  { name: "Himachal Pradesh", isoCode: "HP" },
  { name: "Jharkhand", isoCode: "JH" },
  { name: "Karnataka", isoCode: "KA" },
  { name: "Kerala", isoCode: "KL" },
  { name: "Madhya Pradesh", isoCode: "MP" },
  { name: "Maharashtra", isoCode: "MH" },
  { name: "Manipur", isoCode: "MN" },
  { name: "Meghalaya", isoCode: "ML" },
  { name: "Mizoram", isoCode: "MZ" },
  { name: "Nagaland", isoCode: "NL" },
  { name: "Odisha", isoCode: "OR" },
  { name: "Punjab", isoCode: "PB" },
  { name: "Rajasthan", isoCode: "RJ" },
  { name: "Sikkim", isoCode: "SK" },
  { name: "Tamil Nadu", isoCode: "TN" },
  { name: "Telangana", isoCode: "TG" },
  { name: "Tripura", isoCode: "TR" },
  { name: "Uttar Pradesh", isoCode: "UP" },
  { name: "Uttarakhand", isoCode: "UT" },
  { name: "West Bengal", isoCode: "WB" },
];

export const cities = [
  { name: "Mumbai", state: "Maharashtra" },
  { name: "Delhi", state: "Delhi" },
  { name: "Bangalore", state: "Karnataka" },
  { name: "Hyderabad", state: "Telangana" },
  { name: "Chennai", state: "Tamil Nadu" },
  { name: "Kolkata", state: "West Bengal" },
  { name: "Pune", state: "Maharashtra" },
  { name: "Ahmedabad", state: "Gujarat" },
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Lucknow", state: "Uttar Pradesh" },
  { name: "Kanpur", state: "Uttar Pradesh" },
  { name: "Nagpur", state: "Maharashtra" },
  { name: "Indore", state: "Madhya Pradesh" },
  { name: "Thane", state: "Maharashtra" },
  { name: "Bhopal", state: "Madhya Pradesh" },
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Patna", state: "Bihar" },
  { name: "Vadodara", state: "Gujarat" },
  { name: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Ludhiana", state: "Punjab" },
];
